name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run lint
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fp-tasks:$(date +%s)
